style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/avenga/couper
options:
  commits:
    # filters:
    #   Type:
    #     - feat
    #     - fix
    #     - perf
    #     - refactor
  commit_groups:
     title_maps:
       feat: Features
       Add: Features
       add: Features
       change: Changes
       Fix: Bug Fixes
       Fixup: Bug Fixes
       perf: Performance Improvements
       refactor: Code Refactoring
  header:
    pattern: "^((\\w+)\\s.*)$"
    pattern_maps:
      - Subject
      - Type
  notes:
    keywords:
      - BREAKING CHANGE
