name: Docker

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '.github/workflows/weekly-fuzz.yml'
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'git tag'
        required: true
#        default: ''
jobs:
  build:
    name: build and test container image
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:

    - name: 'wait for tests'
      uses: lewagon/wait-on-check-action@v1.0.0
      with:
        ref: ${{ github.ref }}
        check-name: 'go test & build'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10

    - name: checkout
      uses: actions/checkout@v2
      if: github.event_name != 'workflow_dispatch'

    - name: checkout given tag
      uses: actions/checkout@v2
      if: github.event_name == 'workflow_dispatch'
      with:
        ref: ${{ github.event.inputs.tag }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          couperio/couper
        tags: |
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
          type=semver,pattern={{major}}.{{minor}}
          type=edge,event=branch
          type=raw,enable=${{ github.event_name == 'workflow_dispatch' }},value=${{ github.event.inputs.tag }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and load docker image
      if: github.event_name == 'release' || github.event_name == 'workflow_dispatch' || (github.ref == 'refs/heads/master' && github.event_name == 'push')
      uses: docker/build-push-action@v2
      with:
        context: .
        labels: ${{ steps.meta.outputs.labels }}
        load: true
        tags: 'couper-test-${{ github.ref }}'

    - name: Test container serves index.html # run for edge and release images
      if: github.event_name == 'release' || github.event_name == 'workflow_dispatch' || (github.ref == 'refs/heads/master' && github.event_name == 'push')
      run: |
        docker run -d --rm -p 8080:8080 'couper-test-${{ github.ref }}'
        [[ $(curl --head --location --connect-timeout 5 --write-out %{http_code} --silent --output /dev/null http://localhost:8080/) == 200 ]]

  publish:
    needs: build
    name: build and publish container image
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      # couperio
      C_USERNAME: ${{ secrets.DOCKER_COUPERIO_USERNAME }}
      C_PASSWORD: ${{ secrets.DOCKER_COUPERIO_PASSWORD }}
      # avenga
      A_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      A_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    strategy:
      matrix:
        include:
          - environment: 'couperio' # map with envs since secrets/vars are not supported as matrix values
            image: 'couperio/couper'
            username: C_USERNAME
            password: C_PASSWORD
          - environment: 'avenga'
            image: 'avenga/couper'
            username: A_USERNAME
            password: A_PASSWORD
    steps:
      - name: checkout
        uses: actions/checkout@v2
        if: github.event_name != 'workflow_dispatch'

      - name: checkout given tag
        uses: actions/checkout@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ matrix.image }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=edge,event=branch
            type=raw,enable=${{ github.event_name == 'workflow_dispatch' }},value=${{ github.event.inputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          #registry: ...
          username: ${{ matrix.username }}
          password: ${{ matrix.password }}

      - name: Build & push image with edge tag
        if: github.ref == 'refs/heads/master' && github.event_name == 'push' # due to release branch, pin to master
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ GitHub.event_name != 'pull_request' }}

      - name: Build & push image with specific tag
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ GitHub.event_name != 'pull_request' }}

      - name: Docker Hub Description
        if: github.event_name == 'release'
        uses: peter-evans/dockerhub-description@v2
        with:
          readme-filepath: './DOCKER.md'
          username: '${{ matrix.username }}'
          password: '${{ matrix.password }}'
          repository: ${{ matrix.image }}

  oidc:
    name: trigger couper-oidc-gateway edge build
    needs:
      - build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_COUPER_API_TOKEN }}" \
          https://api.github.com/repos/avenga/couper-oidc-gateway/dispatches \
          -d '{"event_type": "edge-build", "client_payload": { "version": "edge" }}'
